---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/name: gitops-repository-configuration
    app.kubernetes.io/component: cluster-management
    app.kubernetes.io/part-of: platform-management

resources:
- ConfigMap_cluster-gitops-repository-configuration.yaml
