---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/itewk/gitops-hub-and-workers-template-capabilities.git//kustomize/bases/openshift-gitops-operator?ref=main
