---
applicationSet:
  name: group-production
  generatorGitFilePath: groups/production/applications/**/kustomization.yaml
  project: cluster-management
  syncPolicyAutomated: true
  preventCascadingDeletion: false
