---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/name: group-all
    app.kubernetes.io/component: cluster-management
    app.kubernetes.io/part-of: platform-management

resources:
- cluster-management-gitops
