---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: openshift-gitops

placementBindingDefaults:
  name: openshift-gitops

policyDefaults:
  namespace: acm-policies
  consolidateManifests: true
  orderManifests: false
  orderPolicies: false # use manual dependencies because there is a bit of a tree
  generatePlacementWhenInSet: false
  pruneObjectBehavior: None
  complianceType: musthave
  severity: critical
  informGatekeeperPolicies: false

policySetDefaults:
  generatePolicySetPlacement: true

policies:
- name: install-openshift-gitops-operator
  policySets:
  - infrastructure-gitops
  remediationAction: enforce
  manifests:
  - path: policy-manifests/openshift-gitops/install

- name: configure-openshift-gitops
  policySets:
  - infrastructure-gitops
  remediationAction: enforce
  extraDependencies:
  - name: install-openshift-gitops-operator
  manifests:
  - path: policy-manifests/openshift-gitops/configure

- name: validate-openshift-gitops
  policySets:
  - infrastructure-gitops
  remediationAction: inform
  extraDependencies:
  - name: configure-openshift-gitops
  manifests:
  - path: policy-manifests/openshift-gitops/validate-install

- name: deploy-infrastructure-argocd-applications
  policySets:
  - infrastructure-gitops
  remediationAction: enforce
  extraDependencies:
  - name: validate-openshift-gitops
  manifests:
  - path: policy-manifests/openshift-gitops/deploy-applications

- name: deploy-gatekeeper-constraint-templates
  policySets:
  - infrastructure-gitops
  remediationAction: enforce
  manifests:
  - path: policy-manifests/openshift-gitops/validate-applications/ConstraintTemplate_K8sRequiredManifestSubset.yaml
    
- name: validate-infra-apps-healthy-and-synced
  description: Hello world 12
  policySets:
  - infrastructure-gitops
  namespaceSelector:
    include:
    - 'openshift-gitops'
  consolidateManifests: false
  extraDependencies:
  - name: deploy-infrastructure-argocd-applications
  - name: deploy-gatekeeper-constraint-templates
  manifests:
  - path: policy-manifests/openshift-gitops/validate-applications/K8sRequiredManifestSubset_infra-apps-healthy-and-synced.yaml
    remediationAction: enforce

- name: validate-tenant-apps-healthy-and-synced
  policySets:
  - tenant-gitops
  namespaceSelector:
    include:
    - '*'
    exclude:
    - 'openshift-gitops'
  consolidateManifests: false
  extraDependencies:
  - name: deploy-gatekeeper-constraint-templates
  severity: low
  manifests:
  - path: policy-manifests/openshift-gitops/validate-applications/K8sRequiredManifestSubset_tenant-apps-healthy-and-synced.yaml
    remediationAction: enforce

policySets:
- name: infrastructure-gitops
  description: Infrastructure management policies related to deploying, configuring, and monitoring gitops components
- name: tenant-gitops
  description: Tenant management policies related to deploying, configuring, and monitoring gitops components
