---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

# install applications
helmGlobals:
  chartHome: ../../../helm-charts
helmCharts:
- name: application-set
  version: 1.0.0
  valuesFile: values.yaml
