---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# NOTE: need to re-specify here, rather then inheriting from base, so ArgoCD ApplicationSet can read it so in Application template can specify the namespace and create it so that argo can give itself namespace admin
namespace: external-secrets-operator

resources:
- https://github.com/itewk/gitops-hub-and-workers-template-capabilities.git//kustomize/bases/external-secrets-operator?ref=main
