---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/name: acm-hub
    app.kubernetes.io/component: hub
    app.kubernetes.io/part-of: cluster-management

resources:
- MultiClusterHub.yaml
