---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gatekeeper

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/name: gatekeeper
    app.kubernetes.io/component: policy-enforcement
    app.kubernetes.io/part-of: cluster-management

resources:
- Gatekeeper.yaml
