---
# Set the ApplicationSet gitops revision
#
# Source is assuming a resource with /data/gitopsRevision (e.g. ConfigMap)
source:
  name: cluster-gitops-repository-configuration
  fieldPath: .data.gitopsRevision
targets:
  - select:
      group: argoproj.io
      version: v1alpha1
      kind: Application
    fieldPaths:
      - spec.source.targetRevision
    options:
      create: True
