---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/part-of: platform-management

resources:
# deploy cluster gitops applications
- cluster-management-gitops

# deploy tenant gitops applications
- tenant-management-gitops
