---
apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: group
spec:
  text: "group: hub"
  location: BannerTop

  # NOTE: color blind safe colors from https://personal.sron.nl/~pault/#sec:sequential
  color: '#FFFFFF'
  backgroundColor: '#A80003'
