---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/name: web-console
    app.kubernetes.io/component: cluster-customization
    app.kubernetes.io/part-of: platform-management

resources:
- ConsoleNotification_group.yaml
