---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
- https://github.com/itewk/gitops-hub-and-workers-template-capabilities.git//kustomize/bases/cluster-gitops-repository-configuration?ref=main

# Patch gitops configuration for cluster specific configuration (e.g. repository, revision)
patches:
- target:
    name: cluster-gitops-repo-config
  path: ConfigMap-patch_cluster-gitops-repo-config.yaml
