---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/name: configuration
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: gitops

resources:
- ConfigMap_gitops-configuration.yaml
