---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
# load gitops repository configuration (e.g. repository, revision)
- overlays/gitops-repository-configuration

# install applications
- ApplicationSet_cluster-specific.yaml
- ../../../groups/all

# Update ApplicationSets to use the gitops configuration
replacements:
- path: ApplicationSets-replacement_gitopsRepository.yaml
- path: ApplicationSets-replacement_gitopsRevision.yaml
